const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],C={Unit:'#149dff',Source:'#36d65c',Resource:'#ff9f1c',Processor:'#ff3b4f',Logic:'#bd4cff',Buff:'#ff4fa3',Power:'#ffd500',Combinator:'#00d8e8',Boss:'#ff2448',Equipment:'#8ba7bd',Splitter:'#c1c7ce'};
const iconKinds=['unit','land','seed','wheat','stoneSource','stone','ironSource','iron','sawmill','plank','mix','pickaxe','sword','autoMiner','buff','add','multiply','multiply2','number3','portal','if5','splitter','boss','gravityOre','gravityStone','gravityPlant','gravityCore','gravityForge','gravityReactor'],I=Object.fromEntries(iconKinds.map(k=>[k,`assets/node-icons/${k}.png?v=3`]));
function iconHtml(kind){return I[kind]?`<img src="${I[kind]}" alt="" draggable="false">`:'◇'}
function decorateShopIcons(){$$('#tribute .shop-icon').forEach(el=>el.innerHTML=iconHtml('wheat'));$$('#functionNodes [data-func]').forEach(b=>b.querySelector('.shop-icon').innerHTML=iconHtml(b.dataset.func))}
const D={
 unit:{title:'노동자',type:'Unit',desc:'노동력 제공\n음식 연결 시 체력 회복',ins:['Resource'],outs:['Unit','Power'],attack:2,hp:10},
 land:{title:'땅',type:'Source',desc:'노동력 + 씨앗 → 밀\n생산 시간: 10초',ins:['Unit','Resource'],outs:['Source'],key:'wheat',seedKey:'seed',time:10},seed:{title:'씨앗',type:'Resource',desc:'밀 생산에 필요한 종자',ins:[],outs:['Resource'],key:'seed'},wheat:{title:'밀',type:'Resource',desc:'식량 자원 · 노동자 회복',ins:['Source'],outs:['Resource'],key:'wheat',food:true,heal:2},
 stoneSource:{title:'암석 (자원지)',type:'Source',desc:'생산: 돌',ins:['Unit','Buff'],outs:['Source'],key:'stone',time:10},stone:{title:'돌',type:'Resource',desc:'재화 수량',ins:['Source'],outs:['Resource'],key:'stone'},
 ironSource:{title:'철광석 (자원지)',type:'Source',desc:'생산: 철',ins:['Unit','Buff'],outs:['Source'],key:'iron',time:10},iron:{title:'철',type:'Resource',desc:'재화 수량',ins:['Source'],outs:['Resource'],key:'iron'},
 sawmill:{title:'제재소 (가공)',type:'Processor',desc:'목재 2 ➜ 판자 1\n(소요: 5초)',ins:['Resource'],outs:['Processor'],time:5,recipes:[{in:{wood:2},out:{key:'plank',n:1}}]},plank:{title:'판자',type:'Resource',desc:'재화 수량',ins:['Processor'],outs:['Resource'],key:'plank'},
 mix:{title:'Mix (조합)',type:'Logic',desc:'판자1 + 돌1 ➜ 곡괭이1\n철1 + 돌1 ➜ 검1\n(소요: 5초)',ins:['Resource','Resource'],outs:['Logic'],time:5,recipes:[{in:{plank:1,stone:1},out:{key:'pickaxe',n:1}},{in:{iron:1,stone:1},out:{key:'sword',n:1}}]},pickaxe:{title:'곡괭이',type:'Resource',desc:'가공물 수량',ins:['Logic'],outs:['Resource'],key:'pickaxe'},sword:{title:'검 (가공물)',type:'Equipment',desc:'1개 이상 보유 시 Power +3',ins:['Logic'],outs:['Power'],key:'sword',equip:3},
 autoMiner:{title:'자동 채굴기',type:'Unit',desc:'노동력 제공 (자동, 체력 소모 없음)',ins:[],outs:['Unit','Power'],attack:1,hp:999},buff:{title:'과부하 (버프)',type:'Buff',desc:'생산량 +2 버프',ins:[],outs:['Buff'],production:2},
 add:{title:'덧셈기 (연산)',type:'Combinator',desc:'연결된 공격력을 더한다',ins:['Power','Power'],outs:['Power'],op:'add'},multiply:{title:'곱셈기 (연산)',type:'Combinator',desc:'연결된 공격력을 곱한다',ins:['Power','Power'],outs:['Power'],op:'multiply'},multiply2:{title:'곱하기 2 (특수)',type:'Combinator',desc:'연결된 공격력을 2배로 만든다',ins:['Power'],outs:['Power'],op:'multiply2'},number3:{title:'숫자 3 (특수)',type:'Combinator',desc:'입력 없이 공격력 3 출력',ins:[],outs:['Power'],op:'constant'},portal:{title:'포탈 (특수)',type:'Combinator',desc:'공격력을 그대로 전달\n침식 감쇠 면역',ins:['Power'],outs:['Power'],op:'portal'},if5:{title:'IF ≥5 (특수)',type:'Combinator',desc:'5 이상이면 통과, 아니면 0',ins:['Power'],outs:['Power'],op:'if'},
 splitter:{title:'보급 분배기',type:'Splitter',desc:'공급 흐름을 두 경로로 분배',ins:['Any'],outs:['Any','Any']},boss:{title:'중력 붕괴 위기',type:'Boss',desc:'정제되지 않은 중력석 에너지가 복원 구역 전체로 번지고 있습니다.\n안정화 장치를 연결하세요.',ins:['Power'],outs:[],hp:32,radius:180,locked:true},
 gravityOre:{title:'중력석 광맥',type:'Source',desc:'생산: 중력석(원석)\n채굴 중 주변에 위험 반경이 발생합니다.',ins:['Unit','Buff'],outs:['Source'],key:'gravityStone',time:10},gravityStone:{title:'중력석 (원석)',type:'Resource',desc:'미정제 고에너지 광물. 정제 전에는 불안정합니다.',ins:['Source'],outs:['Resource'],key:'gravityStone'},
 gravityPlant:{title:'중력 정제소',type:'Processor',desc:'중력석(원석) 2 ➜ 정제 중력석 1\n(소요: 6초)',ins:['Resource'],outs:['Processor'],time:6,recipes:[{in:{gravityStone:2},out:{key:'gravityCore',n:1}}]},gravityCore:{title:'정제 중력석',type:'Resource',desc:'안정화된 고에너지 결정체',ins:['Processor'],outs:['Resource'],key:'gravityCore'},
 gravityForge:{title:'중력 코어 조립소',type:'Logic',desc:'정제 중력석 2 ➜ 중력 코어 1\n(소요: 6초)',ins:['Resource','Resource'],outs:['Logic'],time:6,recipes:[{in:{gravityCore:2},out:{key:'gravityReactor',n:1}}]},gravityReactor:{title:'중력 코어 발전기',type:'Equipment',desc:'1개 이상 보유 시 Power +8',ins:['Logic'],outs:['Power'],key:'gravityReactor',equip:8}
};
const resourceDef={seed:'seed',wheat:'wheat',wood:'wood',stone:'stone',iron:'iron',plank:'plank',pickaxe:'pickaxe',sword:'sword',gravityStone:'gravityStone',gravityCore:'gravityCore',gravityReactor:'gravityReactor'};
const typeLabel={Unit:'노동력',Source:'생산시설',Resource:'자원',Processor:'가공',Logic:'조합',Buff:'버프',Power:'공격력',Combinator:'연산',Boss:'위기',Equipment:'장비',Splitter:'분배',Any:'범용'};
const portShape={Unit:'circle',Buff:'circle',Splitter:'circle',Any:'circle',Source:'square',Processor:'square',Resource:'diamond',Equipment:'diamond',Power:'triangle',Combinator:'triangle',Logic:'triangle',Boss:'triangle'};
let actx=null;
function audioCtx(){if(!actx)actx=new(window.AudioContext||window.webkitAudioContext)();if(actx.state==='suspended')actx.resume();return actx}
function beep(freq,dur,type,vol,delay){try{let ctx=audioCtx(),t=ctx.currentTime+(delay||0),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type||'square';osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(vol||.1,t+.005);gain.gain.exponentialRampToValueAtTime(.0001,t+(dur||.08));osc.connect(gain);gain.connect(ctx.destination);osc.start(t);osc.stop(t+(dur||.08)+.02)}catch(e){}}
const sfx={
 click:()=>beep(720,.045,'square',.07),
 select:()=>beep(880,.03,'square',.05),
 connect:()=>{beep(660,.05,'square',.09);beep(990,.07,'square',.07,.05)},
 error:()=>{beep(180,.09,'square',.11);beep(140,.13,'square',.11,.09)},
 type:()=>beep(1150+Math.random()*250,.02,'square',.03),
 success:()=>{beep(523,.08,'square',.09);beep(659,.08,'square',.09,.09);beep(784,.14,'square',.1,.18)},
 shake:()=>beep(380,.04,'square',.06),
 packOpen:()=>{beep(300,.07,'sawtooth',.08);beep(600,.08,'square',.09,.07);beep(900,.14,'square',.1,.15)},
 alarm:()=>{beep(220,.16,'sawtooth',.12);beep(220,.16,'sawtooth',.12,.24)},
 bossHit:()=>beep(150,.05,'square',.07),
 victory:()=>[523,659,784,1046].forEach((f,i)=>beep(f,.13,'square',.09,i*.09)),
 gameOver:()=>[392,349,294,220].forEach((f,i)=>beep(f,.2,'sawtooth',.09,i*.15))
};
document.addEventListener('click',e=>{if(e.target.closest('button'))sfx.click()});
const chapters=[{title:'[1라운드] 식량 생산 기반',desc:'목표: 밀 3개 생산',key:'wheat',goal:3,label:'📦 1라운드 보상 팩',cards:[['unit',100,420,'▣ 추가 노동자 1명이 배정되었습니다.'],['land',360,420,'▣ 추가 경작지가 배정되었습니다.'],['seed',620,420,'▣ 씨앗 5개가 추가 지급되었습니다.']],story:[['아리아','밀 3개 생산을 확인했습니다. 제1캠프의 최소 식량 생산성이 기준치를 통과했습니다.'],['시스템 기록','2라운드 기능 승인: 회사 상납 및 크레딧 배급 요청.'],['아리아','식량을 하트웰에 상납하면 크레딧을 얻습니다. 크레딧으로 필요한 신규 노드를 배급 요청할 수 있습니다.']]},{title:'[2라운드] 회사 상납',desc:'목표: 크레딧 30 획득',creditGoal:30,label:'📦 2라운드 보상 팩',cards:[['autoMiner',100,650,'▣ 자동 작업 장비가 승인되었습니다.'],['gravityOre',100,900,'▣ 중력석 광맥 채굴 권한이 승인되었습니다.'],['gravityPlant',600,900,'▣ 중력 정제소 설치가 승인되었습니다.'],['gravityForge',900,900,'▣ 중력 코어 조립소가 지급되었습니다.']],story:[['아리아','복원 사업 지원금 목표를 달성했습니다. 이번 성과를 근거로 하트웰 복원국이 캠프1 지하 방공호 심층부의 신규 채굴권을 승인했습니다. 정찰 도중 고에너지 결정체 — 인턴들 사이에서는 \'중력석\'이라 불리는 광물이 다량 확인되었습니다.','gravityFound'],['아리아','주의하십시오. 중력석 원석은 정제되기 전까지 불안정합니다. 채굴 중 주변 시설에 위험 반경이 발생하므로, 인접 배치 시 손상에 유의하시기 바랍니다. 이는 3단계 실습 평가 항목에 포함됩니다.','gravityHazard'],['아리아','3라운드 실습 목표는 정제 중력석 3개 생산입니다. 원석 채굴부터 정제, 코어 조립까지 전체 공급망을 직접 구성하십시오. 완료 시 캠프1 최초의 고에너지 시스템이 가동됩니다.','gravityMission']]},{title:'[3라운드] 중력석 채굴 사업',desc:'목표: 정제 중력석 3개 생산',key:'gravityCore',goal:3,label:'📦 3라운드 보상 팩',cards:[['gravityOre',100,1150,'▣ 추가 채굴 부지가 승인되었습니다.']],boss:true,complete:'복원 시뮬레이션의 모든 평가 항목을 완료했습니다 — 중력석 기반 에너지 시스템이 정식 가동됩니다.',story:[['아리아','정제 공정 중 예기치 못한 과부하가 발생했습니다 — 중력 코어 발전기의 에너지가 제어를 벗어나고 있습니다. 보유한 모든 동력을 연결해 즉시 안정화하십시오.','gravityBoss']]}];
const historyVisuals={hartwell:['2074','◉  CONTROL','하트웰 통치 개시','감시 · 배급 · 의료 · 치안의 중앙 통제'],intern:['ACCESS 01','⌨  →  SIM','인턴 권한 승인','복원안 시뮬레이션 · 결과 보고'],mission:['MISSION 01','◇  ⇄  ⚙','복원 실습 목표','노동력·자원 연결 · 생산 및 위기 대응 평가'],board:['GUIDE 1/4','▦  +  ◇','복원 보드 접속','노드 = 작업반 · 자원 구역 · 시설'],node:['GUIDE 2/4','✋  →  ◇','노드 조작','드래그 이동 · 박스로 다중 선택'],wire:['GUIDE 3/4','◇  ➜  ◇','포트 연결','출력→입력 드래그 · 진행바 완료 시 생산'],reward:['GUIDE 4/4','▣  →  ★','목표 달성','물자 팩 지급 · 복합 위기 발생'],gravityFound:['DEEP CORE','🌀  →  🔮','중력석 발견','지하 방공호 심층부 · 신규 채굴권 승인'],gravityHazard:['WARNING','⚠  🌀  ⚠','위험 반경 주의','원석 불안정 · 인접 시설 손상 가능'],gravityMission:['MISSION 02','🔮 → 💎 → 🔆','정제 중력석 3개 생산','채굴 → 정제 → 코어 조립'],gravityBoss:['ALERT','🔆  ⚡  ⚠','중력 붕괴 위기','에너지 폭주 · 즉시 대응 필요']};
const historyImages=Object.fromEntries(['hartwell','intern','mission','board','node','wire','reward'].map(k=>[k,`assets/prologue/${k}.png`]));
const intro=[['아리아','2074년, 레비아 하트웰은 “감시와 통제 없이는 인간은 서로를 죽인다”고 선언하며 하트웰 복원국을 세웠습니다. 이후 배급과 치안, 정보망은 모두 중앙 통제 아래 놓였습니다.','hartwell'],['아리아','안녕하세요, 인턴 님. 저는 하트웰 복원국 교육 담당 AI, 아리아입니다. 지금부터 진행되는 과정은 「제1캠프 복원 시뮬레이션 실습」이며, 신규 인턴이 반드시 이수해야 하는 필수 교육입니다. 실습 결과는 인턴 평가 자료로 자동 기록되니 참고하시기 바랍니다.','intern'],['아리아','실습 목표는 간단합니다. 노드로 노동력과 자원을 연결해 복원 사업의 기초 운영 절차를 체득하는 것입니다. 지금부터의 모든 조작, 생산량, 위기 대응 기록은 상부의 실제 복원 결정에 참고 자료로 제출됩니다. 그럼 오리엔테이션을 계속하겠습니다.','mission']];
const boardGuide=[['아리아','[실습 브리핑 1/4] 지금 화면은 복원 보드, 즉 인턴 실습용 작업 화면입니다. 각 노드는 작업반, 자원 구역, 보유 물자 또는 복원 시설을 의미합니다. 교육 과정에 따라 하나씩 안내하겠습니다.','board'],['아리아','[실습 브리핑 2/4] 노드는 드래그해서 이동할 수 있고, 빈 공간을 드래그하면 여러 노드를 한 번에 선택할 수 있습니다. 가운데 버튼을 누른 채 드래그하면 화면이 이동합니다. 실습 중 자유롭게 연습해보시기 바랍니다.','node'],['아리아','[실습 브리핑 3/4] 출력 포트에서 호환되는 입력 포트까지 드래그하면 공급망이 연결됩니다. 진행바가 가득 차면 물자 생산 또는 시설 작업이 완료 처리됩니다. 이는 평가 항목의 핵심 절차이니 반드시 숙지하시기 바랍니다.','wire'],['아리아','[실습 브리핑 4/4] 목표를 달성하면 하트웰이 복원 물자 팩을 지급합니다. 일부 단계에서는 캠프 전체를 위협하는 복합 위기가 발생하니 대응 절차도 함께 평가됩니다. 오리엔테이션을 마칩니다 — 실습을 시작하세요.','reward']];
let G=null,mode='new',slot=-1,timer=null,lastTickAt=performance.now(),drag=null,link=null,armed=null,box=null,panDrag=null,clip=[],clipW=[],pasteN=0,dialogue=null,toastT=null,pendingDelete=-1,packMode='reward',packDone=null;
const fresh=()=>({nodes:[],wires:[],chapter:0,cleared:false,counter:0,main:null,credits:0,starterOpened:false,pan:{x:0,y:0,z:1},paused:false,gameOver:false,selected:[],selectedW:[],selectedR:[]});
function uid(){return'n'+(G.counter++)}function spawn(kind,x,y,extra={}){let n={id:uid(),kind,x:Math.round(x/20)*20,y:Math.round(y/20)*20,count:0,progress:0,processing:false,recipe:-1,erosion:0,radius:D[kind].radius||0,hp:D[kind].hp||0,copy:false,...extra};G.nodes.push(n);return n}function node(id){return G.nodes.find(n=>n.id===id)}function def(n){return D[n.kind]}function saveKey(i){return'nodecraft_html_slot_'+i}
function show(id){['titleScreen','slotScreen','loadingScreen','playScreen'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}function overlay(id,on){$('#'+id).classList.toggle('hidden',!on)}
function fade(fn){$('#fade').classList.add('on');setTimeout(()=>{fn();requestAnimationFrame(()=>$('#fade').classList.remove('on'))},360)}
function openSlots(isNew){mode=isNew?'new':'continue';$('#slotTitle').textContent=isNew?'새 게임 슬롯 선택':'이어하기 슬롯 선택';renderSlots();fade(()=>show('slotScreen'))}
function renderSlots(){let h='';for(let i=0;i<4;i++){let s=loadSlot(i);h+=`<button class="slot" data-slot="${i}" ${!s&&mode==='continue'?'disabled':''}><h3>슬롯 ${i+1}</h3>${s?`<p>${chapters[Math.min(s.chapter,1)].title}</p><p>노드 ${s.nodes.length}개 · ${s.saved||''}</p><span class="delete" data-delete="${i}">삭제</span>`:`<p>비어 있음</p><p>${mode==='new'?'새로운 게임을 시작합니다.':'저장된 게임이 없습니다.'}</p>`}</button>`}$('#slots').innerHTML=h}
function loadSlot(i){try{return JSON.parse(localStorage.getItem(saveKey(i)))}catch{return null}}function checkpoint(){if(slot<0||!G)return;G.saved=new Date().toLocaleString('ko-KR');localStorage.setItem(saveKey(slot),JSON.stringify(G));$('#saveState').textContent='저장 완료';setTimeout(()=>$('#saveState').textContent='자동 저장',900)}
function enter(i){slot=i;show('loadingScreen');setTimeout(()=>{if(mode==='new'){G=fresh();let u=spawn('unit',100,150);G.main=u.id;spawn('land',350,150)}else G=loadSlot(i);if(node(G.main))node(G.main).locked=false;startPlay(mode==='new')},1250)}
function startPlay(isNew){show('playScreen');G.paused=false;G.gameOver=false;G.credits??=0;renderAll();focusMain();clearInterval(timer);timer=setInterval(tick,1000);let tutorial=()=>{if(!localStorage.getItem('nodecraft_tutorial'))overlay('tutorial',true);else $('#firstHint').classList.remove('hidden')};if(isNew)playDialogue(intro,()=>playDialogue(boardGuide,()=>openStarterPack(tutorial)))}
function renderAll(){renderMissions();renderNodes();renderWires();renderZones();renderFields();renderShop();applyView();$('#chapterBadge').textContent=G.chapter<chapters.length?`복원 단계 0${G.chapter+1}`:'평가 완료';$('#firstHint').classList.toggle('hidden',G.wires.length>0)}
function renderMissions(){$('#missions').innerHTML=chapters.map((c,i)=>{let v=c.creditGoal?(G.credits||0):(c.key?resourceTotal(c.key):0),goal=c.creditGoal||c.goal,done=i<G.chapter||(i===G.chapter&&G.cleared);return`<div class="mission ${i>G.chapter?'locked':''} ${done?'done':''}"><h3>${c.title}</h3><p>${c.desc}</p><div class="progress"><i style="width:${Math.min(100,v/goal*100)}%"></i></div><div class="progress-row"><span>${done?'✓ 완료':'진행 중'}</span><span>${v} / ${goal}</span></div></div>`}).join('');let c=chapters[G.chapter];$('#packBtn').classList.toggle('hidden',!c||!G.cleared);if(c)$('#packBtn').textContent=c.label;$('#credits').textContent=`CR ${G.credits||0}`;$('#tributeBtn').classList.toggle('hidden',G.chapter<1);$('#requisitionBtn').classList.toggle('hidden',G.chapter<1);$('#functionBtn').classList.toggle('hidden',G.chapter<1)}
function portHtml(types,dir){return types.map((t,i)=>`<i class="port ${dir}" data-port="${i}" data-dir="${dir}" data-shape="${portShape[t]||'circle'}" style="--port:${C[t]||C.Splitter};top:${42+i*27}px" title="${dir==='in'?'입력':'출력'} · ${typeLabel[t]||t}"></i>`).join('')}
function nodeStatus(n){let d=def(n);if(d.locked||n.locked)return null;if(d.type==='Unit'){if(n.hp>0&&n.hp<=d.hp*.3)return'체력 위험';return null}if(d.type==='Source'){let ins=incoming(n.id),workers=ins.filter(x=>def(x.n).type==='Unit'&&x.n.hp>0);if(!workers.length)return'노동력 필요';if(d.seedKey&&!ins.map(x=>x.n).find(x=>def(x).key===d.seedKey&&x.count>0))return'씨앗 부족';return null}if(['Processor','Logic'].includes(d.type)){if(n.processing)return null;let inputs={};for(let q of incoming(n.id)){let r=resolveResource(q.n.id);if(r)inputs[def(r).key]=r}if(!d.recipes.some(rec=>Object.entries(rec.in).every(([k,v])=>inputs[k]&&inputs[k].count>=v)))return'재료 부족';return null}return null}
function renderNodes(){$('#nodes').innerHTML=G.nodes.map(n=>{let d=def(n),sel=G.selected.includes(n.id),locked=d.locked||n.locked,bar=d.time?Math.min(100,n.progress/d.time*100):0,label=d.type==='Unit'?`HP ${Math.max(0,n.hp)} / ${d.hp}`:d.type==='Resource'||d.type==='Equipment'?`× ${n.count}`:d.type==='Boss'?`HP ${Math.max(0,n.hp)} / ${d.hp}`:power(n.id)>0&&['Combinator','Splitter'].includes(d.type)?`Power ${power(n.id)}`:'',st=nodeStatus(n);return`<article class="node ${sel?'selected':''} ${locked?'locked':''}" data-node="${n.id}" data-kind="${n.kind}" data-type="${d.type}" style="left:${n.x}px;top:${n.y}px;--node:${C[d.type]};filter:brightness(${1-n.erosion*.48})"><div class="node-head"><small>${typeLabel[d.type]||d.type}</small></div><div class="node-body"><span class="node-icon-big" aria-hidden="true">${iconHtml(n.kind)}</span><b class="node-name">${d.title}</b></div>${portHtml(d.ins,'in')}${portHtml(d.outs,'out')}<b class="node-count">${label}</b>${st?`<span class="status-badge" title="${st}">⚠ ${st}</span>`:''}${n.erosion>0?`<span class="erosion"><i style="width:${n.erosion*100}%"></i></span>`:''}<span class="node-progress"><i style="width:${bar}%"></i></span></article>`}).join('')}
function updateProgressBars(now){if(G){let lead=Math.max(0,Math.min(1,(now-lastTickAt)/1000));for(let n of G.nodes){let d=def(n);if(!d.time)continue;let shown=n.progress+(n.processing&&!G.paused?lead*(1-n.erosion):0),fill=$(`.node[data-node="${n.id}"] .node-progress i`);if(fill)fill.style.width=Math.min(100,shown/d.time*100)+'%'}}requestAnimationFrame(updateProgressBars)}
function endpoint(n,dir,i){let el=$(`.node[data-node="${n.id}"] .port.${dir}[data-port="${i}"]`),vr=$('#viewport').getBoundingClientRect(),r=el.getBoundingClientRect();return{x:(r.left+r.width/2-vr.left-G.pan.x)/G.pan.z,y:(r.top+r.height/2-vr.top-G.pan.y)/G.pan.z}}
function path(points){if(points.length===2){let[a,b]=points,dx=Math.max(60,Math.abs(b.x-a.x)*.45);return`M${a.x},${a.y} C${a.x+dx},${a.y} ${b.x-dx},${b.y} ${b.x},${b.y}`}return points.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' ')}
function renderWires(){let h='';for(let i=0;i<G.wires.length;i++){let w=G.wires[i],a=node(w.from),b=node(w.to);if(!a||!b)continue;let pts=[endpoint(a,'out',w.fp),...(w.points||[]),endpoint(b,'in',w.tp)],col=C[def(a).outs[w.fp]]||C.Splitter;h+=`<path class="wire ${G.selectedW.includes(i)?'selected':''}" data-wire="${i}" d="${path(pts)}" stroke="${col}"/>`}if(link){let a=endpoint(node(link.from),'out',link.port);h+=`<path class="wire preview ${link.valid?'valid':'invalid'}" d="${path([a,{x:link.x,y:link.y}])}" stroke="${C[def(node(link.from)).outs[link.port]]||'#aaa'}"/>`}$('#wires').innerHTML=h;$('#wires').querySelectorAll('.wire:not(.preview)').forEach(p=>{p.onclick=e=>selectWire(+p.dataset.wire,e);p.ondblclick=e=>addReroute(+p.dataset.wire,e);p.oncontextmenu=e=>{e.preventDefault();disconnectWire(+p.dataset.wire)}});renderReroutes()}
function disconnectWire(i){if(!G.wires[i])return;G.wires.splice(i,1);G.selectedW=[];renderWires();renderNodes();toast('연결을 해제했습니다.','silent');sfx.shake()}
function renderReroutes(){let h='';G.wires.forEach((w,wi)=>(w.points||[]).forEach((p,pi)=>h+=`<i class="reroute ${G.selectedR.some(r=>r[0]===wi&&r[1]===pi)?'selected':''}" data-w="${wi}" data-p="${pi}" style="left:${p.x}px;top:${p.y}px"></i>`));$('#reroutes').innerHTML=h;$$('.reroute').forEach(el=>el.onpointerdown=e=>{e.stopPropagation();let wi=+el.dataset.w,pi=+el.dataset.p;G.selectedR=e.shiftKey?[...G.selectedR,[wi,pi]]:[[wi,pi]];drag={reroute:[wi,pi]};el.setPointerCapture(e.pointerId)})}
function compatible(a,fp,b,tp){let A=def(a),B=def(b),ot=A.outs[fp],it=B.ins[tp];if(A.type==='Splitter'||B.type==='Splitter')return true;if(ot!==it)return false;if(A.type==='Unit'&&!['Source','Processor','Logic','Combinator','Boss'].includes(B.type))return false;if(A.type==='Source'&&(B.type!=='Resource'||A.key!==B.key))return false;if(A.type==='Resource'&&B.type==='Source')return B.seedKey===A.key;if(A.type==='Resource'&&B.type==='Unit')return !!A.food;if(A.type==='Resource'&&!['Processor','Logic'].includes(B.type))return false;if(['Processor','Logic'].includes(A.type)&&!['Resource','Equipment'].includes(B.type))return false;if(A.type==='Buff'&&!['Source','Processor'].includes(B.type))return false;if(['Combinator','Equipment'].includes(A.type)&&!['Combinator','Boss'].includes(B.type))return false;return a.id!==b.id}
function connect(from,fp,to,tp){let A=def(from);G.wires=G.wires.filter(w=>!(w.to===to.id&&w.tp===tp)&&!((A.type!=='Resource')&&w.from===from.id&&w.fp===fp));G.wires.push({from:from.id,fp,to:to.id,tp,points:[]});burstPort(to.id,tp,'#4caf50');$('#firstHint').classList.add('hidden');toast(`${A.title} → ${def(to).title} 연결`);renderWires()}
function selectWire(i,e){if(e.altKey){disconnectWire(i);return}G.selectedW=e.shiftKey?(G.selectedW.includes(i)?G.selectedW.filter(x=>x!==i):[...G.selectedW,i]):[i];renderWires()}
function addReroute(i,e){let p=screenToWorld(e.clientX,e.clientY);G.wires[i].points.push({x:Math.round(p.x/20)*20,y:Math.round(p.y/20)*20});G.wires[i].points.sort((a,b)=>a.x-b.x);renderWires()}
function screenToWorld(x,y){let r=$('#viewport').getBoundingClientRect();return{x:(x-r.left-G.pan.x)/G.pan.z,y:(y-r.top-G.pan.y)/G.pan.z}}
function updatePortHighlight(){$$('.port.in').forEach(p=>{let el=p.closest('.node'),n=el&&node(el.dataset.node);if(!link||!n){p.classList.remove('port-ok','port-no');return}let ok=compatible(node(link.from),link.port,n,+p.dataset.port);p.classList.toggle('port-ok',ok);p.classList.toggle('port-no',!ok)})}
function applyView(){$('#world').style.transform=`translate(${G.pan.x}px,${G.pan.y}px) scale(${G.pan.z})`;$('#zoomLabel').textContent=Math.round(G.pan.z*100)+'%'}
function renderZones(){$('#zones').innerHTML=G.nodes.filter(n=>def(n).type==='Boss').map(n=>`<div class="zone" style="left:${n.x+87}px;top:${n.y+56}px;width:${n.radius*2}px;height:${n.radius*2}px"></div>`).join('')}
function wheatFields(){let out=[];for(let l of G.nodes.filter(n=>n.kind==='land')){let ins=incoming(l.id),worker=ins.find(x=>x.w.tp===0&&def(x.n).type==='Unit')?.n,seed=ins.find(x=>x.w.tp===1&&def(x.n).key==='seed')?.n,wheat=sourceOutput(l.id,'wheat');if(worker&&seed&&wheat)out.push([worker,seed,l,wheat])}return out}
function renderFields(){$('#fields').innerHTML=wheatFields().map(ns=>{let minX=Math.min(...ns.map(n=>n.x))-22,minY=Math.min(...ns.map(n=>n.y))-38,maxX=Math.max(...ns.map(n=>n.x+174))+22,maxY=Math.max(...ns.map(n=>n.y+140))+22;return`<div class="field" style="left:${minX}px;top:${minY}px;width:${maxX-minX}px;height:${maxY-minY}px"><span class="field-label">🌾 밀 밭</span></div>`}).join('')}
function incoming(id){return G.wires.filter(w=>w.to===id).map(w=>({w,n:node(w.from)})).filter(x=>x.n)}function resources(k){return G.nodes.filter(n=>['Resource','Equipment'].includes(def(n).type)&&def(n).key===k)}function findResource(k){return resources(k)[0]}function resourceTotal(k){return resources(k).reduce((sum,n)=>sum+(n.count||0),0)}function sourceOutput(id,k){for(let w of G.wires){if(w.from!==id)continue;let target=node(w.to);if(target&&def(target).key===k)return target}return null}
function resolveResource(id,seen=new Set){if(seen.has(id))return null;seen.add(id);let n=node(id);if(!n)return null;if(['Resource','Equipment'].includes(def(n).type))return n;if(def(n).type==='Splitter'){let i=incoming(id)[0];return i?resolveResource(i.n.id,seen):null}return null}
function power(id,seen=new Set){if(seen.has(id))return 0;seen.add(id);let n=node(id);if(!n)return 0;let d=def(n),mul=1-n.erosion;if(d.type==='Unit')return Math.round((d.attack||0)*mul);if(d.type==='Equipment')return n.count?Math.round(d.equip*mul):0;if(d.type==='Splitter'){let q=incoming(id)[0];return q?power(q.n.id,seen):0}if(d.type!=='Combinator')return 0;let vals=incoming(id).map(x=>power(x.n.id,new Set(seen))),v=0;if(d.op==='constant')v=3;else if(d.op==='add')v=vals.reduce((a,b)=>a+b,0);else if(d.op==='multiply')v=vals.length?vals.reduce((a,b)=>a*b,1):0;else if(d.op==='multiply2')v=(vals[0]||0)*2;else if(d.op==='if')v=(vals[0]||0)>=5?vals[0]:0;else v=vals[0]||0;return Math.round(v*(d.op==='portal'?1:mul))}
function tick(){if(!G||G.paused||G.gameOver)return;lastTickAt=performance.now();for(let b of G.nodes.filter(n=>def(n).type==='Boss')){b.radius=Math.min(500,b.radius+4);let q=incoming(b.id).find(x=>x.w.tp===0),hit=q?power(q.n.id):0;if(hit){b.hp-=hit;burstAt(b.x+87,b.y+55,'#ff5252',12);sfx.bossHit()}if(b.hp<=0)killBoss(b)}for(let n of [...G.nodes]){let d=def(n);if(d.type==='Boss')continue;let inside=G.nodes.some(b=>def(b).type==='Boss'&&rectOverlap(n,b));n.erosion=Math.max(0,Math.min(1,n.erosion+(inside?.08:-.15)));if(n.erosion>=1){if(n.id===G.main){gameOver();return}else destroyNode(n.id,true)}}for(let n of G.nodes.filter(n=>def(n).type==='Unit'))tickWorker(n);for(let n of G.nodes.filter(n=>def(n).type==='Source'))tickSource(n);for(let n of G.nodes.filter(n=>['Processor','Logic'].includes(def(n).type)))tickRecipe(n);checkMission();if(!drag&&!link&&!box&&!panDrag)renderAll();else{renderMissions();renderZones();renderFields()}}
function rectOverlap(n,b){let cx=b.x+87,cy=b.y+56;return n.x+174>=cx-b.radius&&n.x<=cx+b.radius&&n.y+112>=cy-b.radius&&n.y<=cy+b.radius}
function tickWorker(n){let d=def(n);if(n.hp>=d.hp)return;let food=incoming(n.id).map(x=>x.n).find(x=>def(x).food&&x.count>0);if(food){food.count--;n.hp=Math.min(d.hp,n.hp+(def(food).heal||1));toast(`${d.title}가 ${def(food).title}을 섭취해 체력을 회복했습니다.`)}}
function tickSource(n){let d=def(n),ins=incoming(n.id),workers=ins.filter(x=>def(x.n).type==='Unit'&&x.n.hp>0).map(x=>x.n),work=workers.length+ins.reduce((s,x)=>s+(def(x.n).type==='Buff'?(def(x.n).production||0):0),0),seed=d.seedKey?ins.map(x=>x.n).find(x=>def(x).key===d.seedKey&&x.count>0):null;n.processing=false;work=Math.round(work*(1-n.erosion));if(work<=0||d.seedKey&&!seed)return;let r=sourceOutput(n.id,d.key);if(!r){let vr=$('#viewport').getBoundingClientRect(),rx=n.x+250,ry=n.y,right=(vr.width-G.pan.x)/G.pan.z,bottom=(vr.height-G.pan.y)/G.pan.z;if(rx+174>right){rx=n.x;ry=n.y+160}if(ry+112>bottom){rx=n.x-250;ry=n.y}r=spawn(resourceDef[d.key],rx,ry);G.wires.push({from:n.id,fp:0,to:r.id,tp:0,points:[]});renderAll();burstAt(r.x,r.y+42,'#ffcc00',40)}n.processing=true;n.progress+=1-n.erosion;if(n.progress>=d.time){r.count+=work;if(seed)seed.count--;workers.forEach(w=>w.hp=Math.max(0,w.hp-1));n.progress=0}}
function tickRecipe(n){let d=def(n),inputs={};for(let q of incoming(n.id)){let r=resolveResource(q.n.id);if(r)inputs[def(r).key]=r}if(!n.processing){for(let i=0;i<d.recipes.length;i++){let rec=d.recipes[i],ok=Object.entries(rec.in).every(([k,v])=>inputs[k]&&inputs[k].count>=v),out=findResource(rec.out.key),connected=out&&G.wires.some(w=>w.from===n.id&&w.to===out.id);if(ok&&(!out||connected)){Object.entries(rec.in).forEach(([k,v])=>inputs[k].count-=v);n.processing=true;n.recipe=i;n.progress=0;break}}}if(n.processing){n.progress+=1-n.erosion;if(n.progress>=d.time){let rec=d.recipes[n.recipe],out=findResource(rec.out.key);if(!out){out=spawn(resourceDef[rec.out.key],n.x+220,n.y);G.wires.push({from:n.id,fp:0,to:out.id,tp:0,points:[]})}if(G.wires.some(w=>w.from===n.id&&w.to===out.id))out.count+=rec.out.n;n.processing=false;n.recipe=-1;n.progress=0}}}
function checkMission(){let c=chapters[G.chapter];if(!c||G.cleared)return;let v=c.creditGoal?(G.credits||0):(c.key?resourceTotal(c.key):0),goal=c.creditGoal||c.goal;if(v>=goal){G.cleared=true;checkpoint();toast('라운드 목표 달성 — 보상 팩이 해금되었습니다.','success')}}
function openStarterPack(done){packMode='starter';packDone=done;overlay('packOverlay',true);$('#packTitle').textContent='기본 제공 팩';$('#packBoxText').textContent='클릭하여\n씨앗 5개 수령';$('#cardReveal').classList.add('hidden');$('#packBox').classList.remove('hidden','explode');$('#packBox').style.display='grid'}
function openPack(){let c=chapters[G.chapter];if(!c)return;packMode='reward';G.packIndex=0;overlay('packOverlay',true);$('#packTitle').textContent=`${G.chapter+1}라운드 보상 팩`;$('#packBoxText').textContent=`클릭하여\n카드 ${c.cards.length}장 뽑기`;$('#cardReveal').classList.add('hidden');$('#packBox').classList.remove('hidden','explode');$('#packBox').style.display='grid'}
function showCardReveal(kind,msg){let d=D[kind];$('#cardReveal').classList.remove('hidden');$('#cardReveal').style.setProperty('--accent',C[d.type]);$('#cardGlyph').innerHTML=iconHtml(kind);$('#cardType').textContent=typeLabel[d.type]||d.type;$('#cardName').textContent=d.title;$('#cardMessage').textContent=msg}
function drawCard(){if(packMode==='starter'){if(G.starterOpened)return;G.starterOpened=true;spawn('seed',100,360,{count:5});showCardReveal('seed','땅의 자원 입력 포트에 연결하세요.');$('#packBox').classList.add('explode');burstScreen(innerWidth/2,innerHeight/2,C.Resource,40);sfx.packOpen();renderAll();setTimeout(()=>{overlay('packOverlay',false);packMode='reward';let done=packDone;packDone=null;done?.()},900);return}let c=chapters[G.chapter],entry=c.cards[G.packIndex];if(!entry)return;let[k,x,y,msg]=entry,n=spawn(k,x,y);if(k==='seed')n.count=5;G.packIndex++;showCardReveal(k,msg);$('#packBox').classList.remove('shake');void $('#packBox').offsetWidth;$('#packBox').classList.add('shake');burstScreen(innerWidth/2,innerHeight/2,C[D[k].type],30);sfx.shake();let left=c.cards.length-G.packIndex;if(left)$('#packBoxText').textContent=`${left}장 남음!`;else{$('#packBox').classList.add('explode');sfx.packOpen();setTimeout(finishPack,900)}renderAll()}
function finishPack(){overlay('packOverlay',false);let c=chapters[G.chapter];G.chapter++;G.cleared=false;let done=()=>{if(c.boss){let b=spawn('boss',1700,1050);b.locked=true;focusNode(b);toast('캠프 복합 위기가 발생했습니다!','alarm')}if(G.chapter>=chapters.length)toast(c.complete,'success');checkpoint();renderAll()};c.story?playDialogue(c.story,done):done()}
function playDialogue(lines,done){dialogue={lines,i:0,done,typing:false,full:''};overlay('dialogue',true);showLine()}
function showLine(){let [who,text,visual]=dialogue.lines[dialogue.i];dialogue.full=text;dialogue.typing=true;$('#speaker').textContent=who;$('#dialogueText').textContent='';let card=historyVisuals[visual],view=$('#historyVisual');view.classList.toggle('hidden',!card);if(card){$('#historyYear').textContent=card[0];$('#historyIcon').innerHTML=historyImages[visual]?`<img src="${historyImages[visual]}" alt="${card[2]}">`:card[1];$('#historyTitle').textContent=card[2];$('#historyCaption').textContent=card[3];view.classList.remove('pop');void view.offsetWidth;view.classList.add('pop')}let i=0;clearInterval(dialogue.timer);dialogue.timer=setInterval(()=>{i++;$('#dialogueText').textContent=text.slice(0,i);if(text[i-1]&&text[i-1].trim())sfx.type();if(i>=text.length){clearInterval(dialogue.timer);dialogue.typing=false}},25)}
function advanceDialogue(){if(!dialogue)return;if(dialogue.typing){clearInterval(dialogue.timer);$('#dialogueText').textContent=dialogue.full;dialogue.typing=false;return}dialogue.i++;if(dialogue.i>=dialogue.lines.length){let d=dialogue.done;dialogue=null;overlay('dialogue',false);d?.()}else showLine()}
function killBoss(b){destroyNode(b.id,false);sfx.victory();toast('위기를 해결했습니다! 특수 연산 노드가 기능 노드 탭에서 해금되었습니다.','success');renderAll();checkpoint()}
function gameOver(){G.gameOver=true;clearInterval(timer);overlay('gameOver',true);sfx.gameOver()}function destroyNode(id,fx){let n=node(id);if(!n)return;G.wires=G.wires.filter(w=>w.from!==id&&w.to!==id);G.nodes=G.nodes.filter(x=>x.id!==id);if(fx)burstAt(n.x+87,n.y+55,'#34152e',25)}
function burstAt(x,y,c,n){let r=$('#viewport').getBoundingClientRect();burstScreen(r.left+G.pan.x+x*G.pan.z,r.top+G.pan.y+y*G.pan.z,c,n)}function burstPort(id,p,c){let e=$(`.node[data-node="${id}"] .port.in[data-port="${p}"]`),r=e.getBoundingClientRect();burstScreen(r.left+8,r.top+8,c,18)}function burstScreen(x,y,c,n){for(let i=0;i<n;i++){let p=document.createElement('i'),a=Math.random()*Math.PI*2,d=25+Math.random()*65;p.className='particle';p.style.cssText=`left:${x}px;top:${y}px;--c:${c};--x:${Math.cos(a)*d}px;--y:${Math.sin(a)*d}px`;$('#particles').append(p);setTimeout(()=>p.remove(),700)}}
function toast(t,type){$('#toast').textContent=t;$('#toast').style.opacity=1;clearTimeout(toastT);toastT=setTimeout(()=>$('#toast').style.opacity=0,1800);if(type==='error')sfx.error();else if(type==='success')sfx.success();else if(type==='alarm')sfx.alarm();else if(type!=='silent')sfx.connect()}function focusNode(n){let r=$('#viewport').getBoundingClientRect();G.pan.x=r.width/2-(n.x+87)*G.pan.z;G.pan.y=r.height/2-(n.y+56)*G.pan.z;applyView()}function focusMain(){let n=node(G.main);if(n)focusNode(n)}
function tributeAmount(n,cr){let total=resourceTotal('wheat');if(total<n){toast(`상납할 밀이 부족합니다. (보유 ${total}/${n})`,'error');return}let remain=n;for(let w of resources('wheat')){if(remain<=0)break;let take=Math.min(w.count,remain);w.count-=take;remain-=take}G.credits=(G.credits||0)+cr;toast(`밀 ${n}개 상납 완료 · CR ${cr} 획득`,'success');checkMission();overlay('tribute',false);renderAll();checkpoint()}
const funcNodes={splitter:{cost:15,limit:4,unlock:1},buff:{cost:20,limit:3,unlock:1},add:{cost:20,limit:2,unlock:2},multiply:{cost:35,limit:1,unlock:2},number3:{cost:25,limit:2,unlock:3},portal:{cost:30,limit:2,unlock:3},multiply2:{cost:40,limit:1,unlock:3}};
function renderShop(){let cr=G.credits||0,wheat=resourceTotal('wheat');$('#reqCredits').textContent=`CR ${cr}`;$$('#requisition [data-buy]').forEach(b=>b.disabled=cr<+b.dataset.cost);$('#tribWheat').textContent=`× ${wheat}`;$$('#tribute [data-tribute]').forEach(b=>b.disabled=wheat<+b.dataset.tribute);$('#funcCredits').textContent=`CR ${cr}`;$$('#functionNodes [data-func]').forEach(b=>{let kind=b.dataset.func,cfg=funcNodes[kind],count=G.nodes.filter(n=>n.kind===kind).length,unlocked=G.chapter>=cfg.unlock,limitEl=b.querySelector('.shop-limit');b.classList.toggle('locked-item',!unlocked);b.disabled=!unlocked||count>=cfg.limit||cr<cfg.cost;if(limitEl)limitEl.textContent=unlocked?`${count} / ${cfg.limit}`:`${cfg.unlock}라운드 클리어 해금`})}
function buyNode(kind,cost){if((G.credits||0)<cost){toast('크레딧이 부족합니다.','error');return}G.credits-=cost;let i=G.nodes.length,n=spawn(kind,180+(i%3)*230,420+Math.floor(i/3)*150);if(kind==='seed')n.count=5;overlay('requisition',false);toast(`${D[kind].title} 배급 승인`,'success');renderAll();checkpoint()}
function buyFuncNode(kind){let cfg=funcNodes[kind];if(!cfg||G.chapter<cfg.unlock){toast('아직 해금되지 않았습니다.','error');return}let count=G.nodes.filter(n=>n.kind===kind).length;if(count>=cfg.limit){toast('설치 개수 제한에 도달했습니다.','error');return}if((G.credits||0)<cfg.cost){toast('크레딧이 부족합니다.','error');return}G.credits-=cfg.cost;let i=G.nodes.length;spawn(kind,180+(i%3)*230,420+Math.floor(i/3)*150);overlay('functionNodes',false);toast(`${D[kind].title} 설치 완료`,'success');renderAll();checkpoint()}
function copy(){let ids=G.selected.filter(id=>{let t=def(node(id)).type;return!['Unit','Boss','Resource','Equipment'].includes(t)});clip=ids.map(id=>{let n=node(id);return{kind:n.kind,x:n.x,y:n.y}});clipW=G.wires.filter(w=>ids.includes(w.from)&&ids.includes(w.to)).map(w=>({...w,fi:ids.indexOf(w.from),ti:ids.indexOf(w.to)}));pasteN=0}
function paste(){if(!clip.length)return;pasteN++;let made=clip.map(q=>spawn(q.kind,q.x+30*pasteN,q.y+30*pasteN,{copy:true}));clipW.forEach(w=>G.wires.push({from:made[w.fi].id,fp:w.fp,to:made[w.ti].id,tp:w.tp,points:[]}));G.selected=made.map(n=>n.id);renderAll()}
function removeSelected(){let removed=0,protectedNode=false;for(let id of [...G.selected]){let n=node(id);if(!n)continue;if(!funcNodes[n.kind]){protectedNode=true;continue}destroyNode(id,true);removed++}G.wires=G.wires.filter((_,i)=>!G.selectedW.includes(i));for(let [wi,pi] of [...G.selectedR].sort((a,b)=>b[1]-a[1]))G.wires[wi]?.points.splice(pi,1);G.selected=[];G.selectedW=[];G.selectedR=[];renderAll();if(removed){toast(`${removed}개 노드 삭제 완료`,'silent');sfx.shake();checkpoint()}else if(protectedNode)toast('기능 노드(분배기·연산기·버프)만 삭제할 수 있습니다.','error')}
window.onpointermove=e=>{if(!G)return;if(drag?.reroute){let p=screenToWorld(e.clientX,e.clientY),[wi,pi]=drag.reroute;if(G.wires[wi]?.points[pi])G.wires[wi].points[pi]={x:Math.round(p.x/20)*20,y:Math.round(p.y/20)*20};renderWires()}else if(drag?.starts){let dx=(e.clientX-drag.sx)/G.pan.z,dy=(e.clientY-drag.sy)/G.pan.z;drag.starts.forEach(s=>{let n=node(s.id);if(n&&!def(n).locked&&!n.locked){n.x=Math.round((s.x+dx)/20)*20;n.y=Math.round((s.y+dy)/20)*20;let el=$(`.node[data-node="${n.id}"]`);if(el){el.style.left=n.x+'px';el.style.top=n.y+'px'}}});renderWires();renderZones();renderFields()}if(link){let p=screenToWorld(e.clientX,e.clientY),hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.port.in'),target=hit?.closest('.node');link.x=p.x;link.y=p.y;link.valid=!!(hit&&target&&compatible(node(link.from),link.port,node(target.dataset.node),+hit.dataset.port));renderWires();updatePortHighlight()}if(panDrag){G.pan.x=panDrag.x+e.clientX-panDrag.sx;G.pan.y=panDrag.y+e.clientY-panDrag.sy;applyView()}if(box){box.x2=e.clientX;box.y2=e.clientY;drawBox()}}
window.onpointerup=e=>{let moved=!!drag?.starts;if(drag?.starts){let dx=(e.clientX-drag.sx)/G.pan.z,dy=(e.clientY-drag.sy)/G.pan.z;drag.starts.forEach(s=>{let n=node(s.id);if(n&&!def(n).locked&&!n.locked){n.x=Math.round((s.x+dx)/20)*20;n.y=Math.round((s.y+dy)/20)*20}})}if(link){let hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.port.in'),el=hit?.closest('.node');if(hit&&el&&compatible(node(link.from),link.port,node(el.dataset.node),+hit.dataset.port)){connect(node(link.from),link.port,node(el.dataset.node),+hit.dataset.port);armed=null}link=null;renderWires();updatePortHighlight()}if(box){selectBox();box=null;$('#selectionBox').style.display='none'}drag=null;panDrag=null;if(moved){renderNodes();renderWires();renderZones();renderFields()}}
window.onmousemove=e=>window.onpointermove(e);
window.onmouseup=e=>window.onpointerup(e);
function drawBox(){let r=$('#viewport').getBoundingClientRect(),x=Math.min(box.x,box.x2)-r.left,y=Math.min(box.y,box.y2)-r.top,w=Math.abs(box.x2-box.x),h=Math.abs(box.y2-box.y),el=$('#selectionBox');el.style.cssText=`display:block;left:${x}px;top:${y}px;width:${w}px;height:${h}px`}
function selectBox(){let a={l:Math.min(box.x,box.x2),r:Math.max(box.x,box.x2),t:Math.min(box.y,box.y2),b:Math.max(box.y,box.y2)};G.selected=G.nodes.filter(n=>{let el=$(`.node[data-node="${n.id}"]`);if(!el)return false;let r=el.getBoundingClientRect();return r.right>=a.l&&r.left<=a.r&&r.bottom>=a.t&&r.top<=a.b}).map(n=>n.id);renderNodes()}
$('#viewport').onpointerdown=e=>{let t=e.target,isBackground=t===$('#viewport')||t===$('#world')||t===$('#nodes')||t===$('#wires')||t===$('#zones')||t===$('#reroutes');if(!isBackground||e.defaultPrevented||e.nodeCraftHandled)return;if(e.button===1){e.preventDefault();panDrag={sx:e.clientX,sy:e.clientY,x:G.pan.x,y:G.pan.y}}else if(e.button===0){if(!e.shiftKey){G.selected=[];$$('.node').forEach(x=>x.classList.remove('selected'))}box={x:e.clientX,y:e.clientY,x2:e.clientX,y2:e.clientY}}};$('#viewport').onwheel=e=>{e.preventDefault();let old=G.pan.z,nz=Math.max(.3,Math.min(2.5,old+(e.deltaY<0?.1:-.1))),r=$('#viewport').getBoundingClientRect(),lx=e.clientX-r.left,ly=e.clientY-r.top,cx=(lx-G.pan.x)/old,cy=(ly-G.pan.y)/old;G.pan.z=nz;G.pan.x=lx-cx*nz;G.pan.y=ly-cy*nz;applyView()};$('#viewport').onauxclick=e=>e.preventDefault();
$('#nodes').addEventListener('pointerdown',e=>{let el=e.target.closest('.node');if(!el||e.button!==0)return;e.nodeCraftHandled=true;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();let n=node(el.dataset.node),p=e.target.closest('.port');if(p){let pi=+p.dataset.port;if(p.dataset.dir==='out'){p.setPointerCapture(e.pointerId);let q=screenToWorld(e.clientX,e.clientY);armed={from:n.id,port:pi};link={...armed,x:q.x,y:q.y,valid:false};renderWires();updatePortHighlight()}else if(armed&&compatible(node(armed.from),armed.port,n,pi)){connect(node(armed.from),armed.port,n,pi);armed=null;link=null;updatePortHighlight()}return}if(!e.shiftKey&&!G.selected.includes(n.id))G.selected=[n.id];else if(e.shiftKey)G.selected=G.selected.includes(n.id)?G.selected.filter(x=>x!==n.id):[...G.selected,n.id];$$('.node').forEach(x=>x.classList.toggle('selected',G.selected.includes(x.dataset.node)));if(def(n).locked||n.locked)return;el.setPointerCapture(e.pointerId);drag={sx:e.clientX,sy:e.clientY,starts:G.selected.map(id=>{let q=node(id);return{id,x:q.x,y:q.y}})}});
$('#nodes').addEventListener('mousemove',e=>{let tip=$('#nodeTooltip');if(drag||link||box||panDrag){tip.classList.add('hidden');return}let el=e.target.closest('.node');if(!el){tip.classList.add('hidden');return}let n=node(el.dataset.node);if(!n)return;let d=def(n);tip.innerHTML=`<b>${d.title}</b><small>${typeLabel[d.type]||d.type}</small><p>${d.desc}</p>`;tip.classList.remove('hidden');let gr=$('#viewport').getBoundingClientRect(),nr=el.getBoundingClientRect(),x=nr.right-gr.left+8,y=nr.bottom-gr.top+8,tw=tip.offsetWidth,th=tip.offsetHeight;if(x+tw>gr.width-8)x=nr.left-gr.left-tw-8;if(y+th>gr.height-8)y=nr.top-gr.top-th-8;tip.style.left=x+'px';tip.style.top=y+'px'});
$('#nodes').addEventListener('mouseleave',()=>$('#nodeTooltip').classList.add('hidden'));
document.onkeydown=e=>{if(dialogue&&[' ','Enter'].includes(e.key)){e.preventDefault();advanceDialogue();return}if(!G||$('#playScreen').classList.contains('hidden'))return;if(e.key==='Escape'){G.paused=!G.paused;overlay('pause',G.paused)}if(e.key.toLowerCase()==='f')focusMain();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c')copy();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v')paste();if(['Delete','Backspace'].includes(e.key)){e.preventDefault();removeSelected()}};
$('#newBtn').onclick=()=>openSlots(true);$('#continueBtn').onclick=()=>openSlots(false);$('#quitBtn').onclick=()=>toast('브라우저 탭을 닫으면 게임이 종료됩니다.');$('#slotBack').onclick=()=>fade(()=>show('titleScreen'));$('#slots').onclick=e=>{let del=e.target.closest('[data-delete]');if(del){e.stopPropagation();pendingDelete=+del.dataset.delete;$('#confirmText').textContent=`슬롯 ${pendingDelete+1} 세이브를 삭제할까요? 이 작업은 되돌릴 수 없습니다.`;overlay('confirm',true);return}let s=e.target.closest('[data-slot]');if(s&&!s.disabled)enter(+s.dataset.slot)};$('#confirmDelete').onclick=()=>{localStorage.removeItem(saveKey(pendingDelete));overlay('confirm',false);renderSlots()};$('#cancelDelete').onclick=()=>overlay('confirm',false);$('#packBtn').onclick=openPack;$('#packBox').onclick=drawCard;$('#dialogue').onclick=advanceDialogue;$('#tutorialBtn').onclick=()=>overlay('tutorial',true);$('#tutorialClose').onclick=()=>{localStorage.setItem('nodecraft_tutorial','1');overlay('tutorial',false)};$('[data-close="tutorial"]').onclick=$('#tutorialClose').onclick;$('#pauseBtn').onclick=()=>{G.paused=true;overlay('pause',true)};$('#resumeBtn').onclick=()=>{G.paused=false;overlay('pause',false)};$('#pauseTutorial').onclick=()=>overlay('tutorial',true);$('#titleBtn').onclick=()=>{G.paused=false;checkpoint();clearInterval(timer);overlay('pause',false);fade(()=>show('titleScreen'))};$('#focusBtn').onclick=focusMain;$('#checkpointBtn').onclick=()=>{overlay('gameOver',false);G=loadSlot(slot)||fresh();startPlay(false)};$('#gameOverTitle').onclick=()=>{overlay('gameOver',false);show('titleScreen')};window.addEventListener('beforeunload',()=>{if(G&&!G.gameOver)checkpoint()});
$('#tributeBtn').onclick=()=>{renderShop();overlay('tribute',true)};$('[data-close="tribute"]').onclick=()=>overlay('tribute',false);$('#tribute').onclick=e=>{let b=e.target.closest('[data-tribute]');if(b&&!b.disabled)tributeAmount(+b.dataset.tribute,+b.dataset.cost)};$('#requisitionBtn').onclick=()=>{renderShop();overlay('requisition',true)};$('[data-close="requisition"]').onclick=()=>overlay('requisition',false);$('#requisition').onclick=e=>{let b=e.target.closest('[data-buy]');if(b&&!b.disabled)buyNode(b.dataset.buy,+b.dataset.cost)};$('#functionBtn').onclick=()=>{renderShop();overlay('functionNodes',true)};$('[data-close="functionNodes"]').onclick=()=>overlay('functionNodes',false);$('#functionNodes').onclick=e=>{let b=e.target.closest('[data-func]');if(b&&!b.disabled)buyFuncNode(b.dataset.func)};
decorateShopIcons();$('#continueBtn').disabled=![0,1,2,3].some(i=>loadSlot(i));show('titleScreen');requestAnimationFrame(updateProgressBars);
